// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		double less = 0 ;
		double more = 0 ; 
		while (N>0)
		{
			double num = Math.random();
			if (num <= 0.5)
			{
				less++;
			}
			else
			 {
				more++;
			 }
			N--;
		}
		if (less>more)
		{
		double ratio  = more/less;	
			System.out.println("> 0.5: " + (int)less + " times");
			System.out.println("<= 0.5: " + (int)more + " times");
			System.out.println("Ratio = " + ratio);
		}
		if (more>less)
		{
			double ratio = less/more;
			System.out.println("> 0.5: " + (int)less + " times");
			System.out.println("<= 0.5: " + (int)more + " times");
			System.out.println("Ratio = " + ratio );
		}
		if (more ==less)
		{
			System.out.println("> 0.5: " + (int)less + " times");
			System.out.println("<= 0.5: " + (int)more + " times" );
		}
		
		 
	}
}
